### ISSUE TITLE
FrontEnd Crash - Zabbix 4.0 

### ISSUE THREAD

**Issue by hygorgaldino** [SpawW/everyz#100]
Após a instalação do EveryZ no zabbix 4.0 (appliance virtual box) o frontend não é carregado e não apresenta erro.

Teria que realizar algum procedimento diferente para instalar no zabbix 4.0 ?!?! Os mesmos passos na appliance da versão 3.4 funcionou normalmente.

**Comment by SpawW** [comment]
Boa noite Hygor, 
   O EveryZ não foi ajustado para o Zabbix 4.0 ainda... recomendo restaurar o frontend.

**Comment by hygorgaldino** [comment]
Obrigado pelo retorno!

Tem previsão da adaptação para o zabbix 4.0? Ou se é que vai ocorrer !?

**Comment by SpawW** [comment]
Estou desenvolvendo a nova versão.
Toda versão .0 do Zabbix importa significativo trabalho a mais para a adaptação... mas vai sair sim.
