### ISSUE TITLE
Suporte ao oracle database

### ISSUE THREAD

**Issue by mauriciorezende20** [SpawW/everyz#101]
Boa tarde.
Utilizo zabbix em um BD oracle e gostaria de adaptar o projeto para podermos usar o recurso de mapas. 
Até o momento o projeto não suporta BD oracle. Alguma sugestão de como realizar essa adaptação? Seria apenas uma conversão das query usadas pelo MySQL nos arquivos PHP? Caso positivo, quais arquivos serão necessários alterar?
Parabéns pelo trabalho.

**Comment by SpawW** [comment]
Mauricio, tem que compatibilizar algumas querys sim... e tem que ter pessoas dispostas a testar com o oracle... mysql... postgress até temos pessoas que testam... mas oracle são muito poucas as que usam com zabbix no mundo.
