### ISSUE TITLE
The layout.htmlpage.menu.php PHP Parse error

### ISSUE THREAD

**Issue by IHeilig** [SpawW/everyz#104]
I have installed the plugin and getting this error when trying to open Zabbix Frontend:
```
PHP Parse error:  syntax error, unexpected '(' in /usr/share/zabbix/app/views/layout.htmlpage.menu.php on line 78
```
Environment:
CentOS 7
Zabbix 4.0.1
Apache/2.4.6

**Comment by cncpt7** [comment]
Unfortunately, it doesn't support the Zabbix 4.x version yet.

**Comment by SpawW** [comment]
@IHeilig , please use this branch: https://github.com/SpawW/everyz/tree/2019-2.0
Its working for 4.0.15
@cncpt7
