### ISSUE TITLE
ZabGeo - Validação de requisitos mínimos para apresentação do mapa

### ISSUE THREAD

**Issue by SpawW** [SpawW/everyz#25]
Adicionar regra de validação para verificar se o conjunto mínimo de dados que possibilita a apresentação correta de um mapa está presente.
Sugestões de validação:
- Hosts ausentes
- Hosts sem dados geograficos
- Ausência de configuração (Key da API, Icone default)

**Comment by aristotelesaraujo** [comment]
Foi atribuído valores automáticos, caso latitude e longitude não tenham sido atribuidos;
Group Zabbix server é selecionado automaticamente caso não tenha nenhum grupo selecionado;

**Comment by SpawW** [comment]
Implementado. Mas pode ser melhorado no futuro com alertas discretos.
