### ISSUE TITLE
ZabGeo - Modelo de dados para os hosts

### ISSUE THREAD

**Issue by aristotelesaraujo** [SpawW/everyz#29]
Definir o modelo dos dados apresentado no popup dos hosts

**Comment by aristotelesaraujo** [comment]
Host: Zabbix Server
IP: 192.168.1.10
Latitude: -3.77827
Longitude: -38.48099
Status: Ok

**Comment by aristotelesaraujo** [comment]
hostname(latLong)
------------------------
Event 1
Event 2

**Comment by SpawW** [comment]
Ajustado e implementado.
