### ISSUE TITLE
Importação de themas

### ISSUE THREAD

**Issue by glctech** [SpawW/everyz#60]
1 - Adicionar no profile (somente do admin), dentro do menu de temas, um link para importar arquivo .css
2- No arquivo css, será alterado somente, cor, fonte e logotipo. (de acordo com o layout da empresa)
3- Padronizar um tamanho para importa logotipos de empresas.

**Comment by gcavalcante8808** [comment]
@mikimba @SpawW Por que não um campo para que os Administradores possam especificar CSS adicional?

A questão maior é fazer o carregamento desse CSS na página do zabbix ... Afinal este seria incluído diretamente no campo header do html.

**Comment by SpawW** [comment]
Foi adicionado um arquivo css "everyz.css" onde podem ser adicionados estilos. ;)
Ele é carregado depois dos arquivos nativos ;)

**Comment by glctech** [comment]
aeeeeeeeee, o brigado!!!!!!!

logo logo terei mais ideias pra ajudar!!!!!

2017-03-07 16:24 GMT-03:00 Adail Horst <notifications@github.com>:

**Comment by glctech** [comment]
isso vai facilitar demais a vida, melhor que ficar caçando o Código linha por linha. rsrsrsr
