### ISSUE TITLE
Bug Zabbix 3.4

### ISSUE THREAD

**Issue by fbenatti** [SpawW/everyz#96]
I have two error after the installation Zabbix 3.4.1
My definitions:

Zabbix verion: Zabbix 3.4.1
Server: Centos 6

1º error: The flow message:
define (‘EVERYZ_VERSION’,’1.1.2′);
Configuration file error
Incorrect value “MYSQL” for DB type. Possible values ZBX_DB_DB2, ZBX_DB_MYSQL, ZBX_DB_ORACLE, ZBX_DB_POSTGRESQL.

Solution:
change /etc/zabbix/web/zabbix.conf.php the $DB[“TYPE”] to ‘ZBX_DB_MYSQL’;
2º error: The flow message:
define (‘EVERYZ_VERSION’,’1.1.2′);
Database error
The frontend does not match Zabbix database. Current database version (mandatory/optional): 3040000/3040000. Required mandatory version: 0. Contact your system administrator.

I can´t resolve this problem, I need reinstall the zabbix-web.

**Comment by SpawW** [comment]
Hi Fernando,
   This appear be a incomplete Zabbix Upgrade Process, with this information I cannot see relation with EveryZ.

   Your ZABBIX is installed from Source or packages ? 
   After upgrade of ZABBIX you restart zabbix_server process and look at zabbix_server.log for upgrade messages and is Everithing is ok (you found sucess on 100% of DB upgrade? )
   After the binary and DB upgrade, you upgrade / access the frontend and works fine ? 

   Only after done this steps... you can try to install EveryZ.
 
   Only after this

**Comment by fbenatti** [comment]
Packets Installeds:
![image](https://user-images.githubusercontent.com/17545722/30651221-f8964104-9e1c-11e7-9e04-96e7e77dd391.png)

Zabbix is a new database and new installation:
![image](https://user-images.githubusercontent.com/17545722/30651321-406ec834-9e1d-11e7-846f-c3e2a84ad6a1.png)

Zabbix operation before install packets of EveryZ:

![image](https://user-images.githubusercontent.com/17545722/30651460-ab4d2646-9e1d-11e7-8b27-f07a7d75e356.png)

Install process:
![image](https://user-images.githubusercontent.com/17545722/30651548-f02bb8b8-9e1d-11e7-9256-296723704f03.png)
![image](https://user-images.githubusercontent.com/17545722/30651568-07650ea8-9e1e-11e7-8c2a-9262bbcefbcf.png)
![image](https://user-images.githubusercontent.com/17545722/30651592-188d17a2-9e1e-11e7-8796-e4eaa5a11865.png)

![image](https://user-images.githubusercontent.com/17545722/30651640-3d6e7106-9e1e-11e7-9269-60f714f3cc42.png)

![image](https://user-images.githubusercontent.com/17545722/30651656-47b6c4c4-9e1e-11e7-96fd-ccb1ef3fd061.png)

![image](https://user-images.githubusercontent.com/17545722/30651674-546ddc2a-9e1e-11e7-8d80-e00e5b2d0d8a.png)
![image](https://user-images.githubusercontent.com/17545722/30651700-691d9cb4-9e1e-11e7-801b-b85cda22ec2b.png)
![image](https://user-images.githubusercontent.com/17545722/30651744-7e26aa9c-9e1e-11e7-82a0-3133f4bd4f83.png)

The fist error:
![image](https://user-images.githubusercontent.com/17545722/30651808-ac06c5fa-9e1e-11e7-879d-98ee47f0201a.png)

Now, For resolve, I needed reinstall zabbix-web, how you can see, I didn't  DB Upgrade, the problem happen after the installation EveryZ.

**Comment by fbenatti** [comment]
I found the solution, you need do:

![image](https://user-images.githubusercontent.com/17545722/30653838-1cb1827c-9e24-11e7-8410-96ac7b0053d8.png)
"""#cp /usr/share/zabbix/include/defines.inc.php /usr/share/zabbix/include/defines.inc.php.old"""

Before installing EveryZ.

Thanks.

**Comment by SpawW** [comment]
Fbenatti,

   Please try to install again ? I reproduce and solve the problem.
