### ISSUE TITLE
Link Everyz fica sobrepondo os demais na aba (Zabbix 3.4.6)

### ISSUE THREAD

**Issue by jrpradojr** [SpawW/everyz#98]
Após migrar da versão 3.2 para 3.4.6 e reinstalar o Everyz notei que após clicar no link Extras e depois tentar mudar para qualquer outra pagina o link Everyz fica sobrepondo os demais até eu clicar em qualquer outro link. O menu some depois que acesso qualquer outro link, voltando para estado normal.

Passos para reproduzir.
1- Acessar Monitoring  - > Dashboard
2- Clicar em Extras (Onde já exibido o link Everyz)
Neste ponto o Menu Everyz já fica travado.
3- Clicar em Monitoring (Pronto, o link Everyz está sobrepondo o Dashboard)

Dados do sistema que ocorre o problema:
Windows 10
Firefox 57.0.4 (64-bit)
Zabbix 3.4.6

Imagens:
Passo 1- 
![image](https://user-images.githubusercontent.com/31750084/35099554-969d12d0-fc3f-11e7-8f36-f94d646b060a.png)

Passo 2- 
![image](https://user-images.githubusercontent.com/31750084/35099578-a79e7df8-fc3f-11e7-83e1-0164d995c2c6.png)

Passo 3-
![image](https://user-images.githubusercontent.com/31750084/35099588-b5f54e7c-fc3f-11e7-9849-ebd2a7660b42.png)

**Comment by ghost** [comment]
Tá acontecendo a mesma coisa no meu.
Centos 7
Zabbix 3.4.6

**Comment by SpawW** [comment]
@jotapesaraiva @git-jrprado 
Muito obrigado pelos reports e desculpem a demora em resolver.
Solicito por favor que instalem novamente e verifiquem se o problema foi resolvido no ambiente de vocês!
A Zabbix alterou o javascript de controle de menus em um ponto que afetava a inserção de novos menus, aqui no ambiente de testes parece ter resolvido.

**Comment by SpawW** [comment]
Confirmado que o problema foi resolvido.
